### ISSUE TITLE
Hackathon prep

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#249]
We're going to be presenting interledger.rs to a bunch of developers at a hackathon in the beginning of October. In order to provide a good experience, we need to:

 - [x] Get the ILP Address from a parent node https://github.com/interledger-rs/interledger-rs/issues/248
- [x] Finish changing the config and CLI options https://github.com/interledger-rs/interledger-rs/pull/236
- [x] Have a basic API for getting incoming payment notifications https://github.com/interledger-rs/interledger-rs/issues/197
- [ ] HTTP API for quoting https://github.com/interledger-rs/interledger-rs/issues/255
- [x] Decide if we want to break any existing endpoints (for example, moving or changing the `/pay` endpoint to be more RESTful) https://github.com/interledger-rs/interledger-rs/issues/258
- [x] Either support BTP account creation (implement [BTP open signup](https://github.com/interledger-rs/interledger-rs/blob/19fbf52034ce49f825c2b457a26d0927091606e5/crates/interledger-btp/src/server.rs#L95) for the Redis store and include that in the `node`) or pre-load accounts on the testnet nodes https://github.com/interledger-rs/interledger-rs/issues/260
- [x] Decide how new nodes will connect to testnet nodes (automatic or manual?) https://github.com/interledger-rs/interledger-rs/issues/261
- [x] Make sure upstream node is set as default route https://github.com/interledger-rs/interledger-rs/issues/332
- [x] Recommend running `localtunnel` alongside the node (or bundle it in the Docker image) to expose the API and SPSP endpoint https://github.com/interledger-rs/interledger-rs/issues/265
- [x] Release docker images and/or binaries to make installation easier https://github.com/interledger-rs/interledger-rs/issues/179
- [x] Have multiple Settlement Engines supported on the testnet
- [x] Provide instructions for installing, running, and configuring different Settlement Engines (or bundle them with the node) https://github.com/interledger-rs/interledger-rs/issues/263
- [ ] Review all documentation https://github.com/interledger-rs/interledger-rs/issues/239
- [x] Write a guide describing how to use interledger.rs to connect to the testnet https://github.com/interledger-rs/interledger-rs/issues/262
- [x] Connect to a BTP server when an account with a `btp_uri` is added https://github.com/interledger-rs/interledger-rs/issues/285

Anything else?

**Comment by bstrie** [comment]
Is there an issue open describing the desired changes to the /pay endpoint?

**Comment by dora-gt** [comment]
I'm so sorry for taking time for so long on doing my tasks (#198, #179, #113, #206, #171, #194, #215, #209).
https://github.com/dora-gt/interledger-rs/wiki/Milestone-2

After the last call, I thought I would probably be able to finish this in 2 weeks but it seems difficult because I have only 1 day left. CLI stuff is closer to finish but Dockerizing and making `.md`s testable would remain unsolved.

**Comment by emschwartz** [comment]
> Is there an issue open describing the desired changes to the /pay endpoint?

Created https://github.com/interledger-rs/interledger-rs/issues/258
